//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionServicios.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionServicios.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        internal static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la dirección de la calle..
        /// </summary>
        internal static string CalleError {
            get {
                return ResourceManager.GetString("CalleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear servicio.
        /// </summary>
        internal static string CrearServicio {
            get {
                return ResourceManager.GetString("CrearServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir una descripción..
        /// </summary>
        internal static string DescripcionError {
            get {
                return ResourceManager.GetString("DescripcionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la fecha..
        /// </summary>
        internal static string FechaError {
            get {
                return ResourceManager.GetString("FechaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce el número.
        /// </summary>
        internal static string IntroducirNumero {
            get {
                return ResourceManager.GetString("IntroducirNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce el TIP.
        /// </summary>
        internal static string IntroducirTip {
            get {
                return ResourceManager.GetString("IntroducirTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        internal static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la matrícula no es correcto (ej: 0000-AAA)..
        /// </summary>
        internal static string MatriculaFormatoError {
            get {
                return ResourceManager.GetString("MatriculaFormatoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la matrícula del vehículo..
        /// </summary>
        internal static string MatriculaVaciaError {
            get {
                return ResourceManager.GetString("MatriculaVaciaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de servicios.
        /// </summary>
        internal static string NombreApp {
            get {
                return ResourceManager.GetString("NombreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir el número de la calle..
        /// </summary>
        internal static string NumeroCalleError {
            get {
                return ResourceManager.GetString("NumeroCalleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        internal static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes indicar el propietario del vehículo..
        /// </summary>
        internal static string PropietarioError {
            get {
                return ResourceManager.GetString("PropietarioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        internal static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la calle.
        /// </summary>
        internal static string SeleccionaCalle {
            get {
                return ResourceManager.GetString("SeleccionaCalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir el TIP del agente..
        /// </summary>
        internal static string TipError {
            get {
                return ResourceManager.GetString("TipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehículos.
        /// </summary>
        internal static string Vehiculos {
            get {
                return ResourceManager.GetString("Vehiculos", resourceCulture);
            }
        }
    }
}
