//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace GestionServicios.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class AppResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("GestionServicios.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        internal static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la dirección de la calle..
        /// </summary>
        internal static string CalleError {
            get {
                return ResourceManager.GetString("CalleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear servicio.
        /// </summary>
        internal static string CrearServicio {
            get {
                return ResourceManager.GetString("CrearServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir una descripción..
        /// </summary>
        internal static string DescripcionError {
            get {
                return ResourceManager.GetString("DescripcionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la fecha..
        /// </summary>
        internal static string FechaError {
            get {
                return ResourceManager.GetString("FechaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        internal static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la matrícula no es correcto (ej: 0000-AAA)..
        /// </summary>
        internal static string MatriculaFormatoError {
            get {
                return ResourceManager.GetString("MatriculaFormatoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la matrícula del vehículo..
        /// </summary>
        internal static string MatriculaVaciaError {
            get {
                return ResourceManager.GetString("MatriculaVaciaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de servicios.
        /// </summary>
        internal static string NombreApp {
            get {
                return ResourceManager.GetString("NombreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir el número de la calle..
        /// </summary>
        internal static string NumeroCalleError {
            get {
                return ResourceManager.GetString("NumeroCalleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        internal static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes indicar el propietario del vehículo..
        /// </summary>
        internal static string PropietarioError {
            get {
                return ResourceManager.GetString("PropietarioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        internal static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir el TIP del agente..
        /// </summary>
        internal static string TipError {
            get {
                return ResourceManager.GetString("TipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehículos.
        /// </summary>
        internal static string Vehiculos {
            get {
                return ResourceManager.GetString("Vehiculos", resourceCulture);
            }
        }
    }
}
